# #Array operations

In [3]:
#Addition
import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.array([9,4,5,6])

add=arr1+arr2
print(add)

add2=arr1[2]+arr2[1]
print(add2)

[10  6  8 10]
7


In [5]:
#Substraction
import numpy as np

arr1=np.array([10,9,8,7])
arr2=np.array([4,5,6,3])

sub=arr1-arr2
print(sub)

[6 4 2 4]


In [7]:
#Multiplication
import numpy as np

arr1=np.array([2,7,4,3])
arr2=np.array([4,5,6,3])

mult=arr1*arr2
print(mult)

[ 8 35 24  9]


In [8]:
#Division
import numpy as np

arr1=np.array([10,8,6,4])
arr2=np.array([5,4,3,2])

Div=arr1/arr2
print(Div)


[2. 2. 2. 2.]


In [13]:
#Broadcasting
#Broadcasting simplifies mathematical operations on arrays with different shapes.
#It enables NumPy to efficiently apply operations element-wise 
#without explicitly copying or reshaping data. 
import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.ones(4)
arr3=np.array([[1,8,30,28],[2,3,4,5]])

add=arr1+arr2
sub=arr1-arr2
Mult=arr1*arr3
div=arr3/arr1

print(add)
print(sub)
print(Mult)
print(div)

[2. 3. 4. 5.]
[0. 1. 2. 3.]
[[  1  16  90 112]
 [  2   6  12  20]]
[[ 1.          4.         10.          7.        ]
 [ 2.          1.5         1.33333333  1.25      ]]


In [16]:
#Element wise operation
import numpy as np

arr1=np.array([4,256,64])
print(np.sqrt(arr1[1]))#np.sqrt() function
print(np.sqrt(arr1))


16.0
[ 2. 16.  8.]


In [20]:
import numpy as np

arr=np.array([30,0,60,90])
print(np.sin(arr))#np.sin() function
print(np.cos(arr))

[-0.98803162  0.         -0.30481062  0.89399666]
[ 0.15425145  1.         -0.95241298 -0.44807362]
[-6.4053312   0.          0.32004039 -1.99520041]


In [21]:
import numpy as np
arr=np.array([1,2,3,4])
print(np.exp(arr))#np.exe() function

[ 2.71828183  7.3890561  20.08553692 54.59815003]
