# #Array shaping and Reshaping

In [11]:
#checking array dimension
import numpy as np

arr=np.array([1,2,3,4])
print("Array Dimension is:",arr.ndim)
print("No of element:",arr.shape)

arr2=np.array([[1,2,3], [3,4,5]])
print("Array Dimension is:",arr2.ndim)
print("No of element:",arr2.shape)

arr3=np.array([[[1,2,3],[2,3,4]], [[6,5,7],[2,3,4]]])
print("Array Dimension is:",arr3.ndim)
print("No of element:",arr3.shape)

Array Dimension is: 1
No of element: (4,)
Array Dimension is: 2
No of element: (2, 3)
Array Dimension is: 3
No of element: (2, 2, 3)


In [17]:
#change array shape
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

narr=arr.reshape(3,4)
print(narr)

narr1=arr.reshape(2,3,2)
print(narr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


[1 2 3 4 5]


In [20]:
import numpy as np

arr=np.array([[1,2,3],[3,4,5]])
narr=arr.flatten()#flatten()
print(narr)

[1 2 3 3 4 5]


# #Array transpose()

In [24]:

import numpy as np
 
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
 
# before transpose
print(arr)
 
# after transpose
print(arr.transpose())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# concatenate() in array

In [26]:
import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.array([4,5,6,7])

narr=np.concatenate((arr1,arr2))
print(narr)

[1 2 3 4 4 5 6 7]


In [27]:
import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.array([4,5,6,7])

narr=np.hstack((arr1,arr2))
print(narr)

[1 2 3 4 4 5 6 7]


In [28]:
import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.array([4,5,6,7])

narr=np.vstack((arr1,arr2))
print(narr)

[[1 2 3 4]
 [4 5 6 7]]


# #Array split()

In [30]:
import numpy as np

arr=np.array([1,2,3,4,5,6])

narr=np.array_split(arr,2)

print(narr)

[array([1, 2, 3]), array([4, 5, 6])]


In [32]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2:]) 

[[ 3  4  5]
 [ 8  9 10]]
