# Introduction to numpy
*NumPy is a Python library used for working with arrays.
*NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
*NumPy stands for Numerical Python
*NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.
*In Python we have lists that serve the purpose of arrays, but they are slow to process.
*NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
*NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
*NumPy is commonly used within data science in order to work through numerical analyses and functions, such as creating and working with arrays, returning descriptive statistics, and a variety of machine learning models and mathematical formulas.

In [2]:
import numpy as np

print(np.__version__)


1.16.5


# # Arrays in numpy
*NumPy is used to work with arrays. The array object in NumPy is called ndarray.
*We can create a NumPy ndarray object by using the array() function.
*To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.
*0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
*An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
*An array that has 1-D arrays as its elements is called a 2-D array.
*An array that has 2-D arrays (matrices) as its elements is called 3-D array.
*NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
*An array can have any number of dimensions.
*When the array is created, you can define the number of dimensions by using the ndmin argument

In [26]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

arr2=np.array([[1,2],[2,3]])
print(arr2)

[1 2 3 4]
[[1 2]
 [2 3]]


In [12]:
#np.zeros()
import numpy as np

arr=np.zeros([3])#1-D zeros array
print(arr)

arr2=np.zeros([3,5])#2-D zeros array
print(arr2)

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
#np.ones()
import numpy as np

arr=np.ones([2])
print(arr)

arr2=np.ones([3,3])
print(arr2)

[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#numpy.arange() function creates an array of evenly spaced values within a given interval. 
#It is similar to Python’s built-in range() function but returns a NumPy array instead of a list.

import numpy as np

arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [20]:
#linspace() function in NumPy returns an array of evenly spaced numbers over a specified range. 
import numpy as np

arr=np.linspace(0,1,num=10)
print(arr)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# # Array Indexing and slicing

In [28]:
#Indexing
import numpy as np

arr=np.array([1,2,3,4])
print(arr[2])

arr2=np.array([[1,2,3], [3,4,5]])
print(arr2[0,1], arr2[1,0])
print(arr2[0,-1])#negative indexing


3
2 3
3


In [32]:
#slicing
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr[0:3])

arr2=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2[0:2,1])#From both elements, return index 2             
print(arr2[0:2,0:3])

[1 2 3]
[2 7]
[[1 2 3]
 [6 7 8]]
